/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medicalstore;
import java.awt.Color;

/**
 *
 * @author Anand
 */
public class welcome extends javax.swing.JFrame {

    /**
     * Creates new form welcome
     */
    public welcome() {
        initComponents();
        //this.add(n)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 153));
        jLabel1.setText("WELCOME");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("HOME PAGE");

        lb1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lb1.setForeground(new java.awt.Color(0, 0, 255));
        lb1.setText("SEARCH");
        lb1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lb1MouseDragged(evt);
            }
        });
        lb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lb1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lb1MouseReleased(evt);
            }
        });
        lb1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lb1KeyPressed(evt);
            }
        });

        lb2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lb2.setForeground(new java.awt.Color(0, 51, 255));
        lb2.setText("INVOICE");
        lb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb2MouseExited(evt);
            }
        });

        lb3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lb3.setForeground(new java.awt.Color(0, 51, 255));
        lb3.setText("ADD NEW MEDICINES & UPDATE");
        lb3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lb3MousePressed(evt);
            }
        });

        lb5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lb5.setForeground(new java.awt.Color(0, 51, 255));
        lb5.setText("CHANGE PASSWORD");
        lb5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lb5MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb5)
                    .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb3, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 753, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(557, 557, 557)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(474, 474, 474))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(lb3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(lb5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb1MouseEntered
   // ODO add your handling code here:
        lb1.setForeground(Color.red);
        lb1.setOpaque(true);
        lb1.setBackground(Color.yellow);
    }//GEN-LAST:event_lb1MouseEntered

    private void lb1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb1MouseDragged
      
// T  // TODO add your handling code here:
    }//GEN-LAST:event_lb1MouseDragged

    private void lb1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb1MouseReleased
      
    }//GEN-LAST:event_lb1MouseReleased

    private void lb1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb1MouseExited
        lb1.setForeground(Color.blue);
        lb1.setOpaque(false);
    }//GEN-LAST:event_lb1MouseExited

    private void lb2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb2MouseEntered
        // TODO add your handling code here:
         lb2.setForeground(Color.red);
        lb2.setOpaque(true);
        lb2.setBackground(Color.yellow);

    }//GEN-LAST:event_lb2MouseEntered

    private void lb2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb2MouseExited
        // TODO add your handling code here:
         lb2.setForeground(Color.blue);
        lb2.setOpaque(false);
                                 
    }//GEN-LAST:event_lb2MouseExited

    private void lb3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb3MouseEntered
        // TODO add your handling code here:
         lb3.setForeground(Color.red);
        lb3.setOpaque(true);
        lb3.setBackground(Color.yellow);

    }//GEN-LAST:event_lb3MouseEntered

    private void lb5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb5MouseEntered
        // TODO add your handling code here:
         lb5.setForeground(Color.red);
        lb5.setOpaque(true);
        lb5.setBackground(Color.yellow);

    }//GEN-LAST:event_lb5MouseEntered

    private void lb3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb3MouseExited
        // TODO add your handling code here:
         lb3.setForeground(Color.blue);
        lb3.setOpaque(false);
    }//GEN-LAST:event_lb3MouseExited

    private void lb5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb5MouseExited
        // TODO add your handling code here:
         lb5.setForeground(Color.blue);
        lb5.setOpaque(false);
    }//GEN-LAST:event_lb5MouseExited

    private void lb1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lb1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lb1KeyPressed

    private void lb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb1MouseClicked
      
    }//GEN-LAST:event_lb1MouseClicked

    private void lb3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb3MouseClicked
       
    }//GEN-LAST:event_lb3MouseClicked

    private void lb3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb3MousePressed
        this.setVisible(false); 
        insert in =new insert();
        in.setVisible(true);
        
    }//GEN-LAST:event_lb3MousePressed

    private void lb1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb1MousePressed
        this.setVisible(false);
       Search.main(null);
    }//GEN-LAST:event_lb1MousePressed

    private void lb5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb5MousePressed
        
        
    }//GEN-LAST:event_lb5MousePressed

    private void lb5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb5MouseClicked
        this.setVisible(false);
        changepassword.main(null);
        
        
    }//GEN-LAST:event_lb5MouseClicked

    private void lb2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb2MouseClicked
    this.setVisible(false); 
    bill.main(null);
    }//GEN-LAST:event_lb2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb5;
    // End of variables declaration//GEN-END:variables
}
